### ISSUE TITLE
from t1st3/silk-companion to damieng/silk-companion

### ISSUE THREAD

**Issue by t1st3** [damieng/silk-companion#1]
I (@T1st3) initiated the project, and we're now moving owner ship to @damieng, the original author of the icons.

What's done?
- update .json files and README and push to Github https://github.com/damieng/silk-companion/commit/04979c487b039259c68a8d3510b68d428b16df89
- unregister the package from Bower
- re-register the package to Bower
- unregister the package from Packagist
- re-register the package to Packagist, but hook is needed (below)

What's seems OK?
- Github https://github.com/damieng/silk-companion
- Travis-CI https://travis-ci.org/damieng/silk-companion,
- NPM https://www.npmjs.com/package/silk-companion
- David-DM https://david-dm.org/damieng/silk-companion
- Bower http://bower.io/search/?q=silk-companion
- Packagist https://packagist.org/packages/damieng/silk-companion

What's to be done?
- ~~check that Bower cache is updated (48hrs) http://bower.io/search/?q=silk-companion~~
- ~~Create Packagist Hook:~~

~~@damieng , can you go to the settings of the project on Github, then in "Webhooks & services", and create a new service for packagist:~~

~~**user**: damieng~~

~~**token**: can be got in your profile on packagist.org (log in with github auth in 2 clicks...)~~

~~**domain**: packagist.org (no http, just the domain)~~

Then, everything should be OK!

**Comment by damieng** [comment]
Okay, I think that's now been setup!

**Comment by damieng** [comment]
It won't actually let me create damieng/silk-companion on packagist as it says it already exists as t1st3/silk-companion

**Comment by t1st3** [comment]
Yeah, I couldn't re-create on your behalf on Packagist as I did with the others.
I just deleted t1st3/silk-companion on packagist, you're free to re-register it.

Note that there were stil some typos in composer.json, so I created a new tag (0.2.2) with these changes 32f21a08d54c236999a91cd86b7ca413dd664cc3

**Comment by damieng** [comment]
Done and added you as a maintainer there.

**Comment by t1st3** [comment]
Thanks! That's great, we're completely OK on this ownership transfer, thanks for your help.
