### ISSUE TITLE
greenkeeper

### ISSUE THREAD

**Issue by t1st3** [damieng/silk-companion#2]
Hi @damieng 

I'd like to implement `greenkeeper` on the project `silk-companion`.

What the point?
Well, greenkeeper is a robot which makes automatic pull requests when some of our NPM dependencies get updated. Obviously, like with every PR, we can see whether the automatic PR from greenkeeper passes the tests (or not) on Travis-Ci before we accept to merge. In a nutshell, it would make things like my last contribution (https://github.com/damieng/silk-companion/commit/22f122d55d15920d494e4669a7627eb1f97464e1) be made automatically.

I already tried to register `silk-companion` with greenkeeper, but as far as I understand it, you'd have to do it yourself as the owner of the project.

What you need to do?
It's quite simple:
- install greenkeeper globally
  
  > npm install -g greenkeeper
- clone your project, and point the CLI to its root
  
  > git clone https://github.com/damieng/silk-companion.git
  > cd silk-companion
- Register/login to greenkeeper with Github
  
  > greenkeeper login

you will then be prompted with a new browser window, which will want some accreditations from Github.
- Finally, enable greenkeeper for the project

> greenkeeper enable

[relevant info about greenkeeper](http://greenkeeper.io/)

Please let me know if you don't manage to follow these steps (or if you don't want such an automation).

Best

**Comment by damieng** [comment]
Hi, hadn't heard about this but it sounds pretty interesting.  I've gone ahead and completed those steps - let me know if you see any problems.

Thanks!

**Comment by t1st3** [comment]
well, since I updated dependencies a few days ago, it's fair to assume that there was nothing to do for greenkeeper for now. We'll hear about him as soon as one of our dependencies is updated.

Thanks for playing this game anyway!

**Comment by damieng** [comment]
No, thank-you for the taking care of this and gradual introduction to the
world of npm!
